;;;; package.lisp

(defpackage #:bayesian-analysis
  (:use #:cl #:let-plus #:iterate)
  (:export
   #:approximate
   #:model
   #:unknown-prior-type
   #:unknown-sampling-type
   #:mcmc-iterations
   #:initialize-accumulator
   #:initialize-likelihood
   #:data
   #:data-with-sigma
   #:initialize-from-source
   #:y
   #:no-data-points
   #:sigma
   #:f-of-x
   #:get-all-data-slots
   #:get-independent-parameters
   #:get-dependent-parameters
   #:get-error-parameters
   #:update-model-with-results
   #:parameter-result
   #:plot-result
   #:plot-iteration-values
   #:plot-data
   #:incongruent-data
   #:wrong-data-type
   #:wrong-number-of-arguments
   #:get-parameter-description-text
   #:unknown-parameter
   #:define-bayesian-model
   #:define-data-class
   #:metropolis-hastings
   #:find-optimum
   #:get-parameter-results
   #:plot-parameter-distribution
   #:plot-likelihood
   #:new-sample?
   #:cache
   #:get-1d-plot-function
   #:varying/log-of-likelihood
   #:constant/log-of-likelihood
   #:get-prior-for-parameter
   #:gsl-multifit-fdfsolver-alloc
   #:no-parameters-to-marginalize
   #:nlopt
   #:nlopt-result
   #:copy-object
   #:gaussian-prior
   #:mu
   #:*default-sampler*
   #:gaussian-sampler
   #:get-parameter-info
   #:name
   #:median
   #:confidence-level
   #:confidence-min
   #:confidence-max
   #:relative-error
   #:absolute-error
   #:max-counts
   #:binned-data
   #:model-parameters-to-marginalize
   #:plot-result-models
   #:input-model
   #:algorithm
   #:all-model-parameters
   #:*data-transparency*
   #:*2d-data-circle-size*
   #:no-dimensions
   #:calculate-marginal-posterior
   #:odds-ratio-1/2
   #:odds-different-data
   #:with-cached-bindings)
  (:nicknames ba))

